#!/usr/bin/env bash
# Aurora PostgreSQL Serverless v2 배포 스크립트
# Usage:
#   bash infra/deploy.sh deploy       # 스택 생성
#   bash infra/deploy.sh status       # 스택 상태 확인
#   bash infra/deploy.sh outputs      # 엔드포인트/시크릿 ARN 출력
#   bash infra/deploy.sh env          # .env 파일 자동 생성
#   bash infra/deploy.sh delete       # 스택 삭제

set -euo pipefail

STACK_NAME="${STACK_NAME:-agentops-ecommerce-db}"
REGION="${AWS_REGION:-us-east-1}"
TEMPLATE="$(dirname "$0")/aurora.yaml"
COGNITO_STACK="${STACK_PREFIX:-agentops}-cognito"

cmd="${1:-status}"

deploy_cognito() {
    echo "Deploying Cognito stack: $COGNITO_STACK ..."
    aws cloudformation deploy \
        --template-file infra/cognito.yaml \
        --stack-name "$COGNITO_STACK" \
        --capabilities CAPABILITY_IAM \
        --no-fail-on-empty-changeset \
        --region "${AWS_REGION:-us-east-1}"
    echo "Cognito stack deployed."
}

cognito_outputs() {
    aws cloudformation describe-stacks \
        --stack-name "$COGNITO_STACK" \
        --query "Stacks[0].Outputs" \
        --output table \
        --region "${AWS_REGION:-us-east-1}"
}

cognito_env() {
    local pool_id client_id region
    pool_id=$(aws cloudformation describe-stacks --stack-name "$COGNITO_STACK" \
        --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text --region "${AWS_REGION:-us-east-1}")
    client_id=$(aws cloudformation describe-stacks --stack-name "$COGNITO_STACK" \
        --query "Stacks[0].Outputs[?OutputKey=='AppClientId'].OutputValue" --output text --region "${AWS_REGION:-us-east-1}")
    region="${AWS_REGION:-us-east-1}"

    echo ""
    echo "# --- Cognito Auth (add to .env) ---"
    echo "AUTH_MODE=jwt"
    echo "COGNITO_USER_POOL_ID=$pool_id"
    echo "COGNITO_APP_CLIENT_ID=$client_id"
    echo "COGNITO_REGION=$region"
    echo ""
    echo "# --- Frontend (add to frontend/.env) ---"
    echo "VITE_COGNITO_USER_POOL_ID=$pool_id"
    echo "VITE_COGNITO_CLIENT_ID=$client_id"
    echo "VITE_COGNITO_REGION=$region"
}

case "$cmd" in
  deploy)
    echo "Deploying Aurora (private, RDS Data API only, takes ~10-15 min)..."
    aws cloudformation deploy \
      --template-file "$TEMPLATE" \
      --stack-name "$STACK_NAME" \
      --region "$REGION" \
      --capabilities CAPABILITY_IAM
    echo "Deploy complete. Run: bash $0 outputs"
    ;;
  status)
    aws cloudformation describe-stacks \
      --stack-name "$STACK_NAME" \
      --region "$REGION" \
      --query 'Stacks[0].StackStatus' \
      --output text
    ;;
  outputs)
    aws cloudformation describe-stacks \
      --stack-name "$STACK_NAME" \
      --region "$REGION" \
      --query 'Stacks[0].Outputs' \
      --output table
    ;;
  env)
    # .env 파일 자동 생성
    CLUSTER_ARN=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`ClusterArn`].OutputValue' --output text)
    SECRET_ARN=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`SecretArn`].OutputValue' --output text)
    DBNAME=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`DatabaseName`].OutputValue' --output text)
    LAMBDA_ARN=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`ToolRouterFunctionArn`].OutputValue' --output text)
    USAGE_TABLE=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`UsageTableName`].OutputValue' --output text)
    DIRECTORY_TABLE=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`DirectoryTableName`].OutputValue' --output text)
    BUDGET_TABLE=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`BudgetStateTableName`].OutputValue' --output text)
    CHAT_HISTORY_TABLE=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`ChatHistoryTableName`].OutputValue' --output text)
    EVALUATIONS_TABLE=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`EvaluationsTableName`].OutputValue' --output text)
    SESSIONS_TABLE=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`SessionsTableName`].OutputValue' --output text)
    ENV_PATH="$(dirname "$0")/../.env"
    cat > "$ENV_PATH" <<EOF
# Auto-generated by infra/deploy.sh env
AWS_REGION=$REGION
DB_CLUSTER_ARN=$CLUSTER_ARN
DB_SECRET_ARN=$SECRET_ARN
DB_NAME=$DBNAME
TOOL_ROUTER_LAMBDA_ARN=$LAMBDA_ARN
BEDROCK_MODEL_ID=global.anthropic.claude-sonnet-4-6
USAGE_TABLE=$USAGE_TABLE
DIRECTORY_TABLE=$DIRECTORY_TABLE
BUDGET_STATE_TABLE=$BUDGET_TABLE
CHAT_HISTORY_TABLE=$CHAT_HISTORY_TABLE
EVALUATIONS_TABLE=$EVALUATIONS_TABLE
SESSIONS_TABLE=$SESSIONS_TABLE
EOF
    # GATEWAY 관련 env는 gateway 생성 이후 append됨
    echo ".env written: $ENV_PATH"
    cat "$ENV_PATH"
    ;;
  lambda)
    # Lambda 코드 업로드 (CFN placeholder ZipFile을 덮어씀)
    FUNC=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`ToolRouterFunctionArn`].OutputValue' --output text | awk -F: '{print $NF}')
    TMP=$(mktemp -d)
    cp "$(dirname "$0")/lambda/handler.py" "$TMP/"
    (cd "$TMP" && zip -r code.zip handler.py > /dev/null)
    echo "Uploading Lambda code to $FUNC..."
    aws lambda update-function-code --function-name "$FUNC" --zip-file "fileb://$TMP/code.zip" --region "$REGION" --no-cli-pager > /dev/null
    aws lambda wait function-updated --function-name "$FUNC" --region "$REGION"
    rm -rf "$TMP"
    echo "Lambda updated."
    ;;
  delete)
    read -p "Delete stack $STACK_NAME? [y/N] " confirm
    if [[ "$confirm" == "y" ]]; then
      aws cloudformation delete-stack --stack-name "$STACK_NAME" --region "$REGION"
      echo "Delete initiated."
    fi
    ;;
  cognito)
    deploy_cognito ;;
  cognito-env)
    cognito_env ;;
  cognito-outputs)
    cognito_outputs ;;
  *)
    echo "Usage: $0 {deploy|status|outputs|env|lambda|delete|cognito|cognito-env|cognito-outputs}"
    exit 1
    ;;
esac
